### ISSUE TITLE
No openwater data ( roundoff)

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/GEOSgcm_GridComp#621]
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/cca38c1d79e2d4187259b0cf7cdba2dd1fbfc475/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/SaltIntSplitter.F90#L155-L166

When It split, there is no openwater data written. It creates roundoff errors.  We may need to explicitly assign zero values to openwater variables.

**Comment by weiyuan-jiang** [comment]
@sanAkel , Santha, I don't know about this program. When I run remap_restart.py twice, it creates roundoff error in openwater output ( double type of variable). Would you please take a look ?

**Comment by sanAkel** [comment]
Hi @weiyuan-jiang I just assigned @zhaobin74 to this. He wrote the [SaltIntSplitter.F90](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/cca38c1d79e2d4187259b0cf7cdba2dd1fbfc475/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/SaltIntSplitter.F90#L155-L166). 

I suspect there is R4 to R8 and back to R4 kind of conversion going on, @zhaobin74 please comment. Thanks!

**Comment by zhaobin74** [comment]
What kind of round-off error do you get, @weiyuan-jiang? Is the error for coupled model restarts?

This utility splits the old "Super saltwater" restart into openwater part and sea ice part. The FR (ice fraction) is redundant for openwater, since it is just 1-FR, so no FR for openwater is output.

**Comment by mathomp4** [comment]
@zhaobin74 @sanAkel For some background, I was looking to create an S2S-C180-MOM5 to C12-MOM6 test for @weiyuan-jiang's `remap_restarts.py` test suite (as a way to test coupled in to coupled out). When I did so, one test I did was remap the restarts where the only changes were:

1. Change the input *folder*, the inputs were identical, just the location
2. Change the output folder so I didn't overwrite

When I did this I got:
```
$ nccmp -dmfgsB output-S2S-to-c12-MOM6-remap_py-from-yaml-2022Aug16/c12-MOM6.openwater_internal_rst.20210416_00z.nc4 output-S2S-to-c12-MOM6-remap_py-from-yaml-2022Aug16-siteaminputs/c12-MOM6.openwater_internal_rst.20210416_00z.nc4
DIFFER : VARIABLE : APONDN : POSITION : [0,1] : VALUES : 0 <> 1
DIFFER : VARIABLE : ERGICE : POSITION : [1,1,0] : VALUES : 0 <> 1
```
Weirdly, openwater was non-zero-diff even though the inputs were exactly the same! @weiyuan-jiang was able to trace this back.

@weiyuan-jiang then realized you could add a tolerance, and then `nccmp` was happy:

```
nccmp -dmfgsB --tolerance=0.0000001 output-S2S-to-c12-MOM6-remap_py-from-yaml-2022Aug16/c12-MOM6.openwater_internal_rst.20210416_00z.nc4 output-S2S-to-c12-MOM6-remap_py-from-yaml-2022Aug16-siteaminputs/c12-MOM6.openwater_internal_rst.20210416_00z.nc4
Files "output-S2S-to-c12-MOM6-remap_py-from-yaml-2022Aug16/c12-MOM6.openwater_internal_rst.20210416_00z.nc4" and "output-S2S-to-c12-MOM6-remap_py-from-yaml-2022Aug16-siteaminputs/c12-MOM6.openwater_internal_rst.20210416_00z.nc4" are identical.
```

In fact, you can use a very loose tolerance and pass because if you look at, say, `APONDN` in each, one has:
```
 APONDN =
  0, 0, 0, 0, 8.27691180619623e-317, 4.94065645841247e-324, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 4.19807579271307e-320, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
...
```
and the other has:
```
 APONDN =
  0, 0, 0, 0, 1.24742959070051e-316, 4.94065645841247e-324, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 3.95301923237581e-320, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
...
```
They are functionally identical and my guess is the model would read those as zero (absent looking for denormal numbers). But `nccmp` probably can't figure out denormals and is going a bit...nuts. Might just be luck it sees a difference!

@zhaobin74 If you can give me some advice on what to change, I can try it out in my test setup.

**Comment by sanAkel** [comment]
> Thanks @mathomp4 .   @zhaobin74, It seems to me, some double variables are not initialized or written  into the files.

Best to wait until @zhaobin74  adds his input to this.

**Comment by zhaobin74** [comment]
@mathomp4 , thanks for the context.  A few things:
1. Are you sure APONDN and ERGICE are in openwater_internal_rst file? They are sea ice variables and should only be in seaicethermo_internal_rst.
2. If the input restart is from s2s V3, the SaltIntSplitter should NOT be running, since the restarts are already split.
Could you show me where your input files are?
4.

**Comment by sanAkel** [comment]
> @zhaobin74 @sanAkel For some background, I was looking to create an S2S-C180-MOM5 to C12-MOM6 test for @weiyuan-jiang's `remap_restarts.py` test suite (as a way to test coupled in to coupled out). When I did so, one test I did was remap the restarts where the only changes were:
> 
> 
> 
> 1. Change the input *folder*, the inputs were identical, just the location
> 
> 2. Change the output folder so I didn't overwrite
> 
> 
> 

@mathomp4 thanks for adding this detail - very helpful to know what's going on.

However, I am confused!
You seem to be having two restarts at c12-res and you are comparing them. Is that right?

If so, how did you get those 2 restarts at c12? I want to be sure we understand the entire layout! Thanks again.

**Comment by mathomp4** [comment]
> However, I am confused! You seem to be having two restarts at c12-res and you are comparing them. Is that right?
> 
> If so, how did you get those 2 restarts at c12? I want to be sure we understand the entire layout! Thanks again.

I used `remap_restarts.py` to generate them pointing to some S2S restarts I grabbed a while back. 

The YAML is:
```yaml
#
# This template file can be filled with questionary or manually
#
#

input:
  air:
    drymass: 1
    hydrostatic: 0
  shared:
    MERRA-2: false
    agrid: C180
    bcs_dir: /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/Ganymed/MOM5//CF0180x6C_TM0720xTM0410/
    expid: S2S-2_1_ANA_001
    ogrid: 720X410
    rst_dir: /discover/nobackup/mathomp4/Regrid/MOM6-Regridding/input-S2S/
    yyyymmddhh: '2021041600'
  surface:
    zoom: '2'
    wemin: '26'
    # it supports three models: catch, catchcnclm40, catchcnclm45
    catch_model: catch
    catch_tilefile: null
output:
  shared:
    agrid: C12
    bcs_dir: /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/Icarus-NLv3/MOM6//CF0012x6C_TM0072xTM0036/
    expid: c12-MOM6
    ogrid: 72X36
    out_dir: /discover/nobackup/mathomp4/Regrid/MOM6-Regridding/output-S2S-to-c12-MOM6-remap_py-from-yaml-2022Aug16/
  air:
    # remap upper air or not
    remap: true
    nlevel: '72'
  surface:
    split_saltwater: true
    surflay: 50.0
    wemin: '13'
    # remap lake, saltwater, landicet
    remap_water: true
    # remap catch(cn)
    remap_catch: true
    catch_tilefile: null
  analysis:
    bkg: false
    aqua: true
    lcv: false

slurm:
  account: g0620
  qos: debug
  constraint: cas
```

Since I came from S2S, the inputs have a `saltwater_internal_rst` but no `openwater_` or `seaicethermo_`, so I'm guessing `SaltIntSplitter` made them.
